version: '2'
services:
  postgres:
    image: postgres:10.0
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=secret"
      - "POSTGRES_DB=ripple_api"
      
  redis:
    image: redis

  api:
    build: .
    links:
      - redis
      - postgres
    ports:
      - "3000:3000"
    volumes:
      - "./:/usr/app"
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=secret"
      - "POSTGRES_DB=ripple_api"
      - "POSTGRES_HOST=postgres"
      - "REDIS_HOST=redis"
      - "JWT_SECRET=secret"