version: '2'
services:
  postgres:
    image: postgres:10.0
    environment:
      - "POSTGRES_USER"
      - "POSTGRES_PASSWORD"
      - "POSTGRES_DB"
      
  redis:
    image: redis

  api:
    build: .
    links:
      - redis
      - postgres
    ports:
      - "3000:3000"
    command: npm run dev
    volumes:
      - "./:/usr/app"
      - "/usr/app/node_modules"
    environment:
      - "POSTGRES_HOST=postgres"
      - "REDIS_HOST=redis"
      - "NODE_ENV"
      - "POSTGRES_USER"
      - "POSTGRES_PASSWORD"
      - "POSTGRES_DB"
      - "JWT_SECRET"
      - "YOUTUBE_API_KEY"
      - "SOUNDCLOUD_API_KEY"
      